### ISSUE TITLE
HowTo missing

### ISSUE THREAD

**Issue by gman-php** [BrunnerLivio/pokemongo-data-normalizer#3]
Hey,

I've been using an older version of this repo and after git pull, you've changed a lot and also the run commands don't work. 'npm run dev' is gone either way. When I do 'npm run' it lists the available command 'prestart' and 'start'. Both result in an exception:
```
ERROR in ./src/index.ts
Module not found: Error: Can't resolve './components/pokemon/pokemon.parser' in '/home/andy/pokemongo/pokemongo-data-normalizer/src'
 @ ./src/index.ts 6:23-69
```

So either there's something missing or this is not the correct command.
Unfortunately the docs are also not useful, as it's only a generated code doc.

Thanks for the help and greetings,

Andy!

**Comment by BrunnerLivio** [comment]
Yes. The project is still work in progress. I'm currently having trouble with path resolving of webpack, this is why this error exists. Hopefully should be fixed soon!

If you want to rollback to the older version, use [the release 1.0.0](https://github.com/BrunnerLivio/pokemongo-data-normalizer/releases/tag/1.0.0). 

I'm rewriting everything, because a lot of things changed in the GAME_MASTER.  I switched over to TypeScript, so it is easier to generate documents, which show you which outputted model you'll get in the output folder.
